name: deploy-Qiniu-CDN

on:
  push:
    paths:
      - "lib/**"
      - "pubspec.yaml"
      - "pubspec.lock"
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    name: deploy-qiniu
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.5.3
        with:
          channel: stable
          flutter-version: 2.8.1

      - name: Install Dependencies
        run: flutter packages get

      - name: Build for Web
        run: flutter build web

      - name: Deploy
        uses: saltbo/uptoc@master
        with:
          driver: qiniu
          region: cn-east-2
          # endpoint: s3-cn-east-2.qiniucs.com
          bucket: face-savior
          dist: build/web
        env:
          UPTOC_UPLOADER_AK: ${{ secrets.QN_KEY }}
          UPTOC_UPLOADER_SK: ${{ secrets.QN_SECRET }}
